#!/usr/bin/env python

activate_this = '/Users/tal/sandbox/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))

"""
Parses settings.conf and provides top-level script
"""
import os
import sys
import argparse

from ConfigParser import SafeConfigParser

from scripts.db import dbcreate, dbinsert

class config:
    def __init__(self, settings):
        self.settings = settings
    def section(self, section):
        return dict(self.settings.items(section) +
                    self.settings.items('Default'))

def get_args():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class = argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--gps', action='store_true', default=False)
    parser.add_argument('--sms', action='store_true', default=False)
    parser.add_argument('--twitter', action='store_true', default=False)
    parser.add_argument('--fitbit', action='store_true', default=False)
    parser.add_argument('--rescuetime', action='store_true', default=False)
    return parser.parse_args()

def main():
    working = os.path.dirname(__file__)
    args = get_args()
    settings = SafeConfigParser(allow_no_value=True)
    #settings.read(os.path.join(working, 'settings.conf'))
    settings.read('/Users/tal/Code/etcetera/settings.conf')
    conf = config(settings)
    defaultconf = conf.section('Default')
    database = defaultconf['database']
    dbcreate(defaultconf)

    ### GPS ###
    if args.gps:
        from scripts.gps_feed import fetch_gps
        gps_feed = fetch_gps(conf.section('Google Drive'))
        dbinsert(defaultconf, 'gps', gps_feed)
    
    #### SMS #### 
    if args.sms:
        from scripts.sms_feed import fetch_sms
        sms_feed = fetch_sms(conf.section('Google Drive'))
        dbinsert(defaultconf, 'sms', sms_feed)

    #### Twitter ####
    if args.twitter:
        from scripts.twitter_feed import fetch_twitter
        settings.read(os.path.join(working, 'secrets','twitter_secrets.conf'))
        twitter_feed = fetch_twitter(conf.section('Twitter'))
        dbinsert(defaultconf, 'Twitter', twitter_feed)

    #### Fitbit ####
    if args.fitbit:
        from scripts.fitbit_feed import fetch_fitbit
        settings.read(os.path.join(working, 'secrets','fitbit_secrets.conf'))
        fitbit_feed = fetch_fitbit(conf.section('fitbit'))
        dbinsert(defaultconf, 'fitbit_intraday_steps', fitbit_feed)

    ### RescueTime ###
    if args.rescuetime:
        from scripts.rescuetime_feed import fetch_rescuetime
        settings.read(os.path.join(working, 'secrets','rescuetime_secrets.conf'))
        rescuetime_feed = fetch_rescuetime(conf.section('rescuetime'))
        dbinsert(defaultconf, 'rescuetime', rescuetime_feed)

if __name__ == '__main__':
    sys.exit(main())
